[site]
title = "Sihan Chen"
description = "B.Eng. Student in Data Science & Big Data Technology at SCUT"
favicon = "/favicon.svg"
last_updated = "November 22, 2025"

[author]
name = "Sihan Chen"
title = "B.Eng. Student"
institution = "South China University of Technology (SCUT)"
avatar = "/me.png"
email = "202330420212@scut.edu.cn"
location = "Guangzhou, Guangdong, China"
location_url = "https://maps.app.goo.gl/89zacpsrUeCUhhpB9" # 华工国际
location_details = [
  "777 Xingye Blvd, Panyu District,",
  "Guangzhou, Guangdong Province, China"
]

[social]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org/0009-0004-6203-318X"
github = "https://github.com/Serenananah"
linkedin = "https://www.linkedin.com/in/%E6%80%9D%E6%B6%B5-%E9%99%88-82a5a5386/"

[features]
enable_likes = true

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research & Projects"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"